-- 코드를 작성해주세요
SELECT D.ID,
    CASE 
        WHEN D.R <= C.MAX_ID * 0.25 THEN 'CRITICAL'
        WHEN D.R <= C.MAX_ID * 0.5 THEN 'HIGH'
        WHEN D.R <= C.MAX_ID * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM (SELECT 
        ID,
        ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS R
        FROM ECOLI_DATA
     ) D
JOIN (SELECT COUNT(*) AS MAX_ID FROM ECOLI_DATA) AS C
ORDER BY D.ID